services:
  app:
    build:
      context: .
    container_name: sipat-app
    restart: unless-stopped
    ports:
      - "8085:80"
    volumes:
      - ./:/var/www/html
    networks:
      - e-randis-network

networks:
  e-randis-network:
    external: true
    name: e-randis_php_e-randis-network
